services:
  db:
    build: ./docker/postgres
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - movies_admin/.env
    networks:
      - test_net

  web:
    build: ./movies_admin
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static:/usr/src/movies_admin/static
    expose:
      - 8000
    env_file:
      - movies_admin/.env
    depends_on:
      - db
    restart: always
    networks:
      - test_net

  nginx:
    image: nginx:1.19.2
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/configs:/etc/nginx/conf.d:ro
      - static:/static
    depends_on:
      - web
    ports:
      - 80:80

    networks:
      - test_net
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - test_net


networks:
    test_net:
        driver: bridge

volumes:
  postgres_data:
  es_data:
  static:
